// <auto-generated />
using Mango.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Meet",
                            Description = "Product test",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToVNdR-ao3wS7o5AmdkilhQ2zdqOmQ4TSJsQ&usqp=CAU",
                            Name = "Test",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Appetizer",
                            Description = "Product test",
                            ImageUrl = "https://c8.alamy.com/comp/R0P6RH/supermarket-grocery-products-cartoon-R0P6RH.jpg",
                            Name = "Test 2",
                            Price = 13.99
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Desert",
                            Description = "Product test",
                            ImageUrl = "https://cdn1.vectorstock.com/i/1000x1000/33/10/supermarket-products-cartoon-vector-22713310.jpg",
                            Name = "Test 3",
                            Price = 3.9900000000000002
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Entree",
                            Description = "Product test",
                            ImageUrl = "https://cdn2.vectorstock.com/i/1000x1000/33/06/supermarket-products-cartoon-vector-22713306.jpg",
                            Name = "Test 4",
                            Price = 23.989999999999998
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Drink",
                            Description = "Product test",
                            ImageUrl = "https://www.shutterstock.com/shutterstock/photos/2204181003/display_1500/stock-vector-cosmetic-tube-with-abstract-floral-background-skincare-product-packaging-template-hand-drawn-2204181003.jpg",
                            Name = "Test 5",
                            Price = 5.9900000000000002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
